name: On Main

on:
  push:
    branches: [ main ]

jobs:

  image_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set image version
        run: | # short hash for image versioning
          echo "version=$(git describe --always)" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          mvn spring-boot:build-image

      - name: Push Image
        run: |
          docker tag demonstration:0.0.1-SNAPSHOT ghcr.io/${{ github.repository }}:${{ env.version }}
          docker push ghcr.io/${{ github.repository }}:${{ env.version }}
