name: On Pull Request to Main

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout detached HEAD
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17 '
          distribution: 'temurin'
          cache: maven

      - name: Maven Build
        run: mvn -B package --file pom.xml
